name = "suorai"
main = "src/index.ts"
compatibility_date = "2026-05-13"

[[kv_namespaces]]
binding = "BONGHOEY_KV"
id = "bfe8e607f77a494fb082a82a2fd89c89"

# This enables native Workers AI
[ai]
binding = "AI"
